import React from "react";

export default function VoiceOutput(){
  return (
    <div className="card">
      <h2>Voice Output</h2>
      <p>The audio generated by TTS will appear here (after you click Synthesize).</p>
    </div>
  )
}
