rootProject.name = 'VoxoraMobile'

// 1. Handles autolinking
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); 
applyNativeModulesSettingsGradle(settings)

// 2. Standard Android app inclusion
include ':app'

// 3. Links the internal React Native Gradle logic
includeBuild('../node_modules/@react-native/gradle-plugin') 

// 4. MANUAL OVERRIDE FOR WORKLETS
include ':react-native-worklets-core'
project(':react-native-worklets-core').projectDir = new File(rootProject.projectDir, '../node_modules/react-native-worklets-core/android')